CREATE TABLE AKUMADEX (
    id_nivel INTEGER NOT NULL , 
    id_usuario INTEGER NOT NULL , 
    data_descoberta TIMESTAMP NOT NULL 
);

ALTER TABLE AKUMADEX ADD CONSTRAINT PK_AKUMADEX PRIMARY KEY (id_nivel, id_usuario);

CREATE TABLE CATEGORIA (
    id_categoria INTEGER NOT NULL , 
    nome_categoria VARCHAR (50) NOT NULL , 
    ds_categoria TEXT NOT NULL 
);

ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (id_categoria);

CREATE TABLE EVOLUCAO (
    id_evolucao INTEGER NOT NULL , 
    id_nivel INTEGER NOT NULL , 
    qt_instancias INTEGER NOT NULL , 
    nivel_resultado SMALLINT NOT NULL 
);

ALTER TABLE EVOLUCAO ADD CONSTRAINT PK_EVOLUCAO PRIMARY KEY (id_evolucao);

ALTER TABLE EVOLUCAO ADD CONSTRAINT UN_NIVEL_EVOLUCAO UNIQUE (id_nivel, nivel_resultado);

CREATE TABLE FRUTA (
    id_fruta INTEGER NOT NULL , 
    id_nivel INTEGER NOT NULL , 
    id_usuario INTEGER NOT NULL , 
    status_fruta CHAR (1) NOT NULL 
);

ALTER TABLE FRUTA ADD CONSTRAINT PK_FRUTA PRIMARY KEY (id_fruta);

ALTER TABLE FRUTA ADD CONSTRAINT CK_STATUS_FRUTA CHECK (status_fruta IN ('D','S','T'));

CREATE TABLE FRUTA_TROCA (
    id_troca INTEGER NOT NULL , 
    id_fruta INTEGER NOT NULL , 
    papel_fruta CHAR (1) NOT NULL 
);

ALTER TABLE FRUTA_TROCA ADD CONSTRAINT PK_FRUTA_TROCA PRIMARY KEY (id_troca, id_fruta);

ALTER TABLE FRUTA_TROCA ADD CONSTRAINT CK_PAPEL_FRUTA CHECK (papel_fruta IN ('O','S'));

CREATE TABLE HISTORICO (
    id_registro INTEGER NOT NULL , 
    id_grupo INTEGER NOT NULL , 
    id_nivel_fruta INTEGER NOT NULL , 
    tipo_transacao CHAR (1) NOT NULL , 
    origem INTEGER NOT NULL , 
    destino INTEGER NOT NULL , 
    valor_belis INTEGER NOT NULL , 
    data_registro TIMESTAMP NOT NULL 
);

ALTER TABLE HISTORICO ADD CONSTRAINT PK_HISTORICO PRIMARY KEY (id_registro, id_grupo);

ALTER TABLE HISTORICO ADD CONSTRAINT CK_TIPO_TRANSACAO CHECK (tipo_transacao IN ('T', 'C', 'V', 'G')); 

CREATE TABLE MODELO (
    id_modelo INTEGER NOT NULL , 
    id_categoria INTEGER NOT NULL , 
    nome_conhecido VARCHAR (100) NOT NULL , 
    nome_cientifico VARCHAR (100) NOT NULL , 
    max_evolucao SMALLINT NOT NULL 
);

ALTER TABLE MODELO ADD CONSTRAINT PK_MODELO PRIMARY KEY (id_modelo);

CREATE TABLE NIVEL (
    id_nivel INTEGER NOT NULL , 
    id_modelo INTEGER NOT NULL , 
    nome_atribuido VARCHAR (100) , 
    nivel_fruta SMALLINT NOT NULL , 
    raridade_fruta INTEGER NOT NULL , 
    preco_base INTEGER NOT NULL , 
    limite_loja INTEGER NOT NULL , 
    ds_fruta TEXT NOT NULL , 
    img_fruta VARCHAR (255) NOT NULL 
);

ALTER TABLE NIVEL ADD CONSTRAINT PK_NIVEL PRIMARY KEY (id_nivel);

ALTER TABLE NIVEL ADD CONSTRAINT UN_NIVEL_MODELO UNIQUE (id_nivel, id_modelo);

CREATE TABLE PORTADOR (
    id_portador INTEGER NOT NULL , 
    id_modelo INTEGER NOT NULL , 
    nome_portador VARCHAR (100) NOT NULL , 
    portador_vivo CHAR (1) NOT NULL , 
    ds_portador TEXT NOT NULL 
);

ALTER TABLE PORTADOR ADD CONSTRAINT PK_PORTADOR PRIMARY KEY (id_portador);

ALTER TABLE PORTADOR ADD CONSTRAINT CK_PORTADOR_VIVO CHECK (portador_vivo IN ('V', 'M'));

CREATE TABLE TROCA (
    id_troca INTEGER NOT NULL , 
    status_troca CHAR (1) NOT NULL , 
    dt_oferta TIMESTAMP NOT NULL , 
    dt_finalizado TIMESTAMP 
);

ALTER TABLE TROCA ADD CONSTRAINT PK_TROCA PRIMARY KEY (id_troca);

ALTER TABLE TROCA ADD CONSTRAINT CK_STATUS_TROCA CHECK (status_troca IN ('P','A','R','E'));

CREATE TABLE USUARIO (
    id_usuario INTEGER NOT NULL , 
    nome_usuario VARCHAR (50) NOT NULL , 
    email_usuario VARCHAR (100) NOT NULL , 
    hash_senha VARCHAR (255) NOT NULL , 
    qt_belis INTEGER NOT NULL , 
    streak_login INTEGER NOT NULL , 
    ultimo_login TIMESTAMP NOT NULL , 
    email_verificado CHAR (1) NOT NULL , 
    status_usuario CHAR (1) NOT NULL , 
    dt_cadastro TIMESTAMP NOT NULL 
);

ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY (id_usuario);

ALTER TABLE USUARIO ADD CONSTRAINT UN_EMAIL_USUARIO UNIQUE (email_usuario);

ALTER TABLE USUARIO ADD CONSTRAINT UN_NOME_USUARIO UNIQUE (nome_usuario);

ALTER TABLE USUARIO ADD CONSTRAINT CK_STATUS_USUARIO CHECK (status_usuario IN ('A', 'I'));

ALTER TABLE USUARIO ADD CONSTRAINT CK_EMAIL_VERIFICADO CHECK (email_verificado IN ('V','N'));

ALTER TABLE AKUMADEX
ADD CONSTRAINT FK_AKUMADEX_NIVEL
FOREIGN KEY (id_nivel)
REFERENCES NIVEL(id_nivel);

ALTER TABLE AKUMADEX
ADD CONSTRAINT FK_AKUMADEX_USUARIO
FOREIGN KEY (id_usuario)
REFERENCES USUARIO(id_usuario);

ALTER TABLE EVOLUCAO
ADD CONSTRAINT FK_EVOLUCAO_NIVEL
FOREIGN KEY (id_nivel)
REFERENCES NIVEL(id_nivel);

ALTER TABLE FRUTA
ADD CONSTRAINT FK_FRUTA_NIVEL
FOREIGN KEY (id_nivel)
REFERENCES NIVEL(id_nivel);

ALTER TABLE FRUTA_TROCA
ADD CONSTRAINT FK_FRUTA_TROCA_FRUTA
FOREIGN KEY (id_fruta)
REFERENCES FRUTA(id_fruta);

ALTER TABLE FRUTA_TROCA
ADD CONSTRAINT FK_FRUTA_TROCA_TROCA
FOREIGN KEY (id_troca)
REFERENCES TROCA(id_troca);

ALTER TABLE FRUTA
ADD CONSTRAINT FK_FRUTA_USUARIO
FOREIGN KEY (id_usuario)
REFERENCES USUARIO(id_usuario);

ALTER TABLE MODELO
ADD CONSTRAINT FK_MODELO_CATEGORIA
FOREIGN KEY (id_categoria)
REFERENCES CATEGORIA(id_categoria);

ALTER TABLE NIVEL
ADD CONSTRAINT FK_NIVEL_MODELO
FOREIGN KEY (id_modelo)
REFERENCES MODELO(id_modelo);

ALTER TABLE PORTADOR
ADD CONSTRAINT FK_PORTADOR_MODELO
FOREIGN KEY (id_modelo)
REFERENCES MODELO(id_modelo);